apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dp
  annotations:
    kubernetes.io/change-cause: 'nginx:1.21.0'
spec:
  # modify replicas according to your case
  replicas: 5
  strategy:
    type: RollingUpdate #Recreate
    rollingUpdate:
      maxUnavailable: 10%
      maxSurge: 100%
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [nginx-app, httpd-app]}
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: mynginx-con
        image: nginx:1.21.0
        ports:
        - containerPort: 80