apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx
  labels:
    kubernetes.courselabs.co: daemonsets
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: init-html
          image: ubuntu
          command: ['sh', '-c', "sleep 5; echo '<!DOCTYPE html><html><body><h1>I was written by an init container</h1></body></html>' > /html/index.html"]
          volumeMounts:
            - name: html
              mountPath: /html
      containers:
        - image: nginx:1.18-alpine
          name: nginx
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          emptyDir: {}
