apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: mynginx
spec:
  containers:
  - name: mynginx-con
    image: nginx
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 10 #Default 0
      periodSeconds: 5 #Default 10
      timeoutSeconds: 5 #Default 1
      successThreshold: 1 #Default 1
      failureThreshold: 3 #Default 3
