apiVersion: v1
kind: Service
metadata:
  name: my-service-np
spec:
  type: NodePort
  selector:
    app: nginx-app
  ports:
  - protocol: TCP 
    nodePort: 30008   #Port of Node 
    port: 8080 	     #Port of Service
    targetPort: 80 	     #Port of Container