apiVersion: v1
kind: Pod
metadata:
  name: mynginx1
  namespace: panneer1
  labels:
    app: web3
    environment: test
    tier: frontend
spec:
  containers:
  - name: nginx-con
    image: nginx:1.20.0
    ports:
    - containerPort: 80
