apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: mynginx
spec:
  containers:
  - name: mynginx-con
    image: nginx
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy1
      initialDelaySeconds: 5
      periodSeconds: 15
