apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: n1
  labels:
    app: web
spec:
  containers:
   - name: nginx-con
     image: nginx
     ports:
       - containerPort: 80
     resources:
       requests:
         memory: 3000Mi
         cpu: 50m #or 0.05 or 5%

