apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-demo
  namespace: n1
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    persistentvolumeclaims: "1"
    services.loadbalancers: "2"
    services.nodeports: "0"
