apiVersion: v1
kind: Secret
metadata:
  name: dbsecrets
type: Opaque
data:
  user: YWRtaW4=		#base64 encoded value of admin
  password: dGlnZXIxMjM0	#base64 encoded value of tiger1234
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container
      image: nginx
      env:
        - name: USERENV
          valueFrom:
            secretKeyRef:
              name: dbsecrets
              key: user
        - name: MYPASSWORDENV
          valueFrom:
            secretKeyRef:
              name: dbsecrets
              key: password
