apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJzYW5kZWVwc29uaSIsInBhc3N3b3JkIjoiU2FuZGVlcEA3NSIsImF1dGgiOiJjMkZ1WkdWbGNITnZibWs2VTJGdVpHVmxjRUEzTlE9PSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: "2023-04-05T14:13:12Z"
  name: mydockersecret
  namespace: default
  resourceVersion: "49935"
  uid: 15ce9057-48fc-4077-9fb6-16c4a744ffac
type: kubernetes.io/dockerconfigjson
