apiVersion: v1
kind: Pod
metadata:
  name: sharevol
spec:
  containers:
  - name: c1
    image: nginx
    volumeMounts:
      - name: xchange
        mountPath: "/data1"
  - name: c2
    image: redis
    volumeMounts:
      - name: xchange
        mountPath: "/data2"
  volumes:
  - name: xchange
    emptyDir: {}
